In [1]:
import numpy as np 
import faiss  # this will import the faiss library
import pickle

In [17]:
dimension = 128    # dimensions of each vector                         
n = 200    # number of vectors                   
np.random.seed(1)             
db_vectors = np.random.random((n, dimension)).astype('float32')

In [2]:
feature_list = pickle.load(open('data/features-caltech101-mobilenet.pickle',
                                'rb'))

In [19]:
feature_vector=np.array(feature_list)

In [21]:
print(feature_vector)

[[0.02200209 0.         0.04104519 ... 0.03728114 0.00561679 0.04104519]
 [0.0400897  0.         0.02624381 ... 0.0400897  0.0400897  0.00638293]
 [0.04183481 0.02670559 0.04183481 ... 0.04183481 0.00678232 0.03945884]
 ...
 [0.04350879 0.04350879 0.03173753 ... 0.00580542 0.00348936 0.        ]
 [0.045225   0.         0.045225   ... 0.00128717 0.         0.        ]
 [0.02494188 0.         0.04943053 ... 0.0062112  0.         0.        ]]


In [3]:
num_features_per_image = len(feature_list[0])
print("Number of features per image = ", num_features_per_image)

Number of features per image =  1024


In [10]:
nlist = 5  # number of clusters
quantiser = faiss.IndexFlatL2(1024)  
index = faiss.IndexIVFFlat(quantiser, 1024, nlist,   faiss.METRIC_L2)

In [23]:
print(index.is_trained)   # False
index.train(feature_vector)  # train on the database vectors
print(index.ntotal)   # 0
index.add(feature_vector)   # add the vectors and update the index
print(index.is_trained)  # True
print(index.ntotal)   # 200

True
0
True
6410


In [24]:
nprobe = 2  # find 2 most similar clusters
n_query = 10  
k = 3  # return 3 nearest neighbours

In [25]:
np.random.seed(0)   
query_vectors = np.random.random((n_query, 1024)).astype('float32')
distances, indices = index.search(query_vectors, k)

In [26]:
print(distances)

[[310.03036 310.05762 310.0994 ]
 [329.55942 329.73798 329.83386]
 [318.97223 319.0227  319.14825]
 [296.08185 296.13068 296.31976]
 [297.07477 297.1733  297.3188 ]
 [309.86896 310.03046 310.06778]
 [299.9505  299.9654  299.97272]
 [313.69592 313.8492  313.90985]
 [307.73154 308.03104 308.0703 ]
 [322.62918 322.6645  322.78223]]


In [27]:
print(indices)

[[ 238  154  246]
 [ 191   19 5180]
 [ 140  199  385]
 [ 191  140  156]
 [ 140  385  156]
 [ 421   22  140]
 [ 140  385  719]
 [ 191  865  859]
 [ 140  191  154]
 [ 191  140  246]]


In [38]:
import glob
import random
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

In [30]:
filenames = pickle.load(open('data/filenames-caltech101.pickle', 'rb'))

In [52]:
def calculate_faiss_time():
        distances, indices = index.search(feature_vector, 5)

In [53]:
%timeit calculate_faiss_time()

1.92 s ± 61.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
